workflows:
  ios-build:
    name: iOS Build
    environment:
      groups:
        - apple_credentials
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Build IPA
        script: |
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa